version: '3'

tasks:
  run:
    cmds:
      - go run github.com/maddalax/htmgo/cli@latest run
    silent: true

  build:
    cmds:
      - go run github.com/maddalax/htmgo/cli@latest build

  watch:
    cmds:
      - go run github.com/maddalax/htmgo/cli@latest watch
    silent: true